const SEARCH_CITY = 'SEARCH_CITY';
const CLEAN_CITY_NAME = 'CLEAN_CITY_NAME';
const FETCH_WEATHER = 'FETCH_WEATHER';
const ERROR = 'ERROR';

export { CLEAN_CITY_NAME, ERROR, FETCH_WEATHER, SEARCH_CITY };